name: Danger js

on:
  push:
    branches: [ "develop" ]

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
      - run: npm install
      - name: Danger
        run: npx danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.DANGER_TEST_PULL_REQUEST }}
